-- CHANGE COLUMN : 컬럼 변경
ALTER TABLE MyTable13
CHANGE COLUMN Col3 Col13 VARCHAR(20); -- 위험!!

INSERT INTO MyTable13 (Col13) VALUES ('가나다라마바사');

ALTER TABLE MyTable13
CHANGE COLUMN Col13 Col3 VARCHAR(3); -- 위험!! 아예 실행안됨

-- 연습 Col10을 Col20 VARCHAR(20)으로 변경
ALTER TABLE MyTable13
CHANGE COLUMN Col10 Col20 VARCHAR(20);

SELECT * FROM MyTable13;
DESC MyTable13;
