-- NOT NULL : NULL허용안함
CREATE TABLE MyTable17 (
	Col1 INT,
    Col2 INT NOT NULL
);

INSERT INTO MyTable17 (Col1, Col2) VALUES (100,200); -- OK
INSERT INTO MyTable17 (Col2) VALUES (200); -- OK
INSERT INTO MyTable17 (Col1) VALUES (100); -- fail

-- 연습 MyTable18 두개 컬럼, VARCHAR(20) 두번째 컬럼만 NOT NULL 제약사항 적용
CREATE TABLE MyTable18 (
	Col1 VARCHAR(20),
    Col2 VARCHAR(20) NOT NULL
);

DESC MyTable18;

CREATE TABLE MyTable19 (
	Col1 INT DEFAULT 0,
    Col2 INT NOT NULL
);

INSERT INTO MyTable19 (Col1, Col2) VALUES (100,200); -- OK
INSERT INTO MyTable19 (Col2) VALUES (200); -- OK
INSERT INTO MyTable19 (Col1) VALUES (100); -- fail
INSERT INTO MyTable19 (Col1, Col2) VALUES (NULL,200); -- OK

SELECT * FROM MyTable19;

DESC MyTable19;

-- NOT NULL DEFAULT 조합 가능

CREATE TABLE MyTable20 (
	Col1 INT, -- NULL 허용 DEFAULT 없음
    Col2 INT NOT NULL, -- NULL 허용안함 DEFAULT없음
	Col3 INT DEFAULT 0, -- NULL 허용 DEFAULT 0
	Col4 INT NOT NULL DEFAULT 0 -- NULL 허용안함 DEFAULT 0
);

DESC MyTable20;